package d_token is

type token is (pc_procediment,
				pc_funcio,
				pc_inici,
				pc_mentre,
				pc_per,
				pc_si,
				pc_sino,
				pc_fi,
				pc_fer,
				pc_retorna,
				pc_constant,
				pc_tipus,
				pc_coleccio,
				pc_registre,
				pc_es,
				pc_llavors,
				pc_no,
				pc_opcio,
				pc_casos,
				pc_entra,
				pc_surt,
				pc_nou,
				pc_nul,
				pc_excepcio,
				pc_sortida,
				pc_de,
				pc_caracter,
				s_or,	
				Error,
				End_of_Input);
end d_token;