#MAKEFILE DE COMPILADORES, v1.0
#USO DE VARIABLES:
#   CC = compilador

#VARIABLES:
CC = gnatmake

#FUNCIÓN PRINCIPAL:
mi_mkfs	:	compilemon.adb  
			$(CC) compilemon compilemon.adb

clean: 
	rm *.o *.ali ./compilemon u_lexica.adb u_lexica.ads compilemon_*
